int Euler1();
int Euler2();
int Euler3();
int Euler4();
int Euler5();
int Euler6();
int Euler7();
int Euler8();
int Euler9();
long long int Euler10();
int Euler11();
int Euler12();
long long int Euler13();
int Euler14();
long long int Euler15();
int Euler16();
int Euler17();
int Euler18();

int Euler67();
